# Generated by Django 5.2.1 on 2025-05-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_chat_app', '0002_chat_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
