# Generated by Django 5.2.1 on 2025-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_chat_app', '0003_alter_chat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=600),
        ),
    ]
